# Generated by Django 3.2.4 on 2022-04-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('year', models.DateField()),
                ('imdb', models.IntegerField()),
                ('ganre', models.CharField(choices=[('adventure', 'Adventure'), ('comedy', 'Comedy'), ('crime and mystery', 'Crime and mystery'), ('fantasy', 'Fantasy'), ('historical', 'Historical'), ('horror', 'Horror'), ('romance', 'Romance'), ('satire', 'Satire'), ('speculative', 'Speculative'), ('thriller', 'Thriller'), ('western', 'Western'), ('erotic', 'Erotic')], max_length=20)),
                ('actors', models.ManyToManyField(to='movie.Actor')),
            ],
        ),
    ]
