# Generated by Django 3.2.4 on 2022-04-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='watch',
            field=models.IntegerField(default=0),
        ),
    ]
